package university.singlewindow.enums;

public enum RoleName {
    ROLE_STUDENT,
    ROLE_DEANERY,
    ROLE_SUPER_ADMIN,
    ROLE_STAFF,
    ROLE_ARCHIVE,
    ROLE_ACCOUNTING,
    ROLE_DORMITORY,
    ROLE_STUDENT_OK,
    ROLE_NAME_INTER_DEPART,
    ROLE_LIBRARY,
    ROLE_PASSPORT_OFFICER,
    ROLE_DEPARTMENT
}
